# Generated by Django 2.1.2 on 2019-03-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add-on',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-date']},
        ),
    ]